<div id="footer"> 
	<div style="margin: 3px">
	<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="UVDVEG3SA9ZAW">
<input type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet.">
<img alt="" border="0" src="https://www.paypalobjects.com/es_ES/i/scr/pixel.gif" width="1" height="1">
</form>
</div>
  &copy; 2003-<?php echo date('Y'); ?>&nbsp;&nbsp;Equipos de Boulesis.com · <a href="/ayuda/quienes_somos.php">¿Quiénes somos?</a> · <a href="/ayuda/faq/">FAQ</a> · <a href="/contacto/">Escríbenos</a> · <a href="/ayuda/legal.php">Términos de uso</a> · <a href="/ayuda/rss/">XML</a>&nbsp;&nbsp;&nbsp;


<div class="noshow" style="display: none;">
<?php


//<span style="padding-left: 20px;">

if ($selectSection=='boule'){
	include (ROOT_NAV.'/nedstat_boule.inc');
}
else{
	include (ROOT_NAV.'/nedstat_boulesis.inc');
}
?>

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-269650-1";
urchinTracker();
</script>
<script src="/com/astrack.js" type="text/javascript"></script>

</div>

</div>

<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us5.list-manage.com","uuid":"12ce48395852194275af3ac90","lid":"cee43d525d"}) })</script>