<?php
// Idioma: Español ($lang = 'es_ES')

$txt['paginaanterior'] = 'Página anterior';
$txt['paginasiguiente'] = 'Página siguiente';
$txt['artimprimir'] = 'Versión imprimible';
$txt['artimprimirpdf'] = 'Versión en PDF';
$txt['artrecomendar'] = 'Recomendar';
$txt['artbuscar'] = 'Buscar en boulesis.com';
$txt['artenviado'] = 'Envió: ';

$txt['archjpg'] = 'Se puede visualizar en el mismo navegador';
$txt['archdoc'] = 'Programa para abrirlo: Microsoft Word';
$txt['archpdf'] = 'Programa para abrirlo: Adobe Acrobat (Reader) o similares';
$txt['archrtf'] = 'Programa para abrirlo: WordPad o similares';
$txt['archzip'] = 'Programa para abrirlo: WinZip, WinRar o similares';
$txt['archrar'] = 'Programa para abrirlo: WinRar o similares';

$convertChars = array(
	'á'=>'a', 
	'Á'=>'A',
	'é'=>'e',
	'É'=>'E', 
	'í'=>'i',
	'Í'=>'I', 
	'ó'=>'o',
	'Ó'=>'O', 
	'ú'=>'u',
	'Ú'=>'U', 
	'¡'=>'', 
	'¿'=>'', 
	'ñ'=>'n'
	);



?>