<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="description" content="Boulesis.com Filosofía, educación, pensamiento" />
<meta name="author" content="Miguel Santa Olalla" />
<meta name="organization" content="Daniel Primo" />
<meta name="ICBM" content="41.65, -4.75" />
<meta name="geo.position" content="41.65, -4.75" />
<meta name="geo.placename" content="Valladolid" />
<meta name="geo.region" content="ES" />
<meta name="locality" content="ES, Spain" />
<meta name="lang" content="es, com" />
<meta name="keywords" content="boulesis, filosofia, filosofía, enseñanza, educacion, etica, moral, logica, adorno, kant, razon, racionalidad, bitacora, weblog " />
<meta name="DC.title" content="Boulesis" />
<meta name="msnbot" content="noindex, nofollow" />

<!-- <link href="http://www.boulesis.com/boule/index.xml" rel="alternate" type="text/xml" title="RSS 2.0 del Weblog" />	 -->
	
<link href="/" rel="Start" title="Página de Inicio" />
<link href="/didactica/glosario/" rel="Glossary" title="Glosario didáctico" />
<link href="/ayuda/" rel="Help" title="Ayuda de boulesis.com" />
<link href="/ayuda/quienes_somos.php" rel="Author" title="Información sobre Miguel Santa Olalla y Daniel Primo" />
<link href="/buscar/" rel="Search" title="Buscador de boulesis.com" />

<script language="JavaScript" type="text/javascript" src="/com/scripts.js"></script>

<link rel="shortcut icon" href="/favicon.ico" />
<link rel="stylesheet" type="text/css" href="/estilos_boulesis_blue.css" />	
