<!-- Buscador simple -->
<div class="center" style="margin-right:15px; text-align: center;">
<form method="GET" action="http://www.google.com/custom" >
	<input type="text" name="q" size="15" maxlength="255" value="" class="formfield2" style="background-color: #EEE"/><br /><input type="submit" name="sa" value="Buscar" class="formbutton2" style="margin-top: 0px"/>
	<input type="hidden" name="cof" value="AH:left;LH:120;L:http://boulesis.com/media/boulesis_logo_name.gif;LW:135;AWFID:117ed63252e3e414;" />
	<input type="hidden" name="domains" value="boulesis.com" />
	<input type="hidden" name="sitesearch" value="boulesis.com" />
	<input type="hidden" name="hl" value="es" />
	<input type="hidden" name="ie" value="UTF-8" />
</form>
</div>