<div id="top" style="height: 30px;">
  <div id="boulesisname" style="float: left;">
	<a href="/"><img src="/media/boulesis_name_blue.gif" width="125" height="28" border="0" alt="Ir a la pagina principal de Boulesis.com" title="Ir a la pagina principal de Boulesis.com" /></a>
  </div>  
  <div id="topside" style="height: 30px;">
	<div id="menuhor" >
  	<?php echo utf8_encode($menuhor); ?>
  	</div>
  </div>
</div>