


<script src="/com/js/cookiechoices.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function(event) {
    cookieChoices.showCookieConsentBar('Política de cookies',
      'Sí, acepto', 'Leer más', 'http://www.boulesis.com/aviso_cookies.php');
  });
</script>  
<div id="top">
  <div id="logo">
  		<a href="/">
		<img src="/media/logo_boulesis_blue.gif" width="109" height="93" border="0" alt="Boulesis.com. Filosofía, deliberación y pensamiento" title="Boulesis. Filosofía, deliberación y pensamiento" /></a>
  		<h1 visibility="hidden" style="display: none">Boulesis. boulesis.com Filosofía, deliberación y pensamiento. Miguel Santa Olalla Tovar</h1>
  </div>
  <div id="topside">
  	<div id="promo">
  	
  	
  		<h2>filosof&iacute;a, deliberación y pensamiento</h2>
		</div><div id="menuhor">
  		<? echo $menuhor; ?>
  	</div>
  </div>
</div>