<div class="spacer">&nbsp;</div>
    <h2><em>Ayuda</em></h2>
<ul>
	<li><a href="/ayuda">Portada</a></li>
	<li><a href="/ayuda/que_es_boulesis.php">¿Qué es boulesis.com?</a></li>
	<li><a href="/ayuda/quienes_somos.php">¿Quiénes somos?</a></li>
	<li><a href="/ayuda/faq/" title="Preguntas frecuentes">FAQ</a></li>
	<li><a href="/ayuda/mapa/" title="Mapa del sitio web">Mapa web</a></li>
	<li><a href="/ayuda/recomendar/">Recomiéndanos</a></li>
	<li><a href="/ayuda/rss/">RSS boulesis.com</a></li>
	<li><a href="/buscar/">Busca en boulesis</a></li>
	<li><a href="/ayuda/legal.php">Términos de uso</a></li>
	<li><a href="/contacto/">Escríbenos</a></li>
</ul>
<div class="spacer">&nbsp;</div>
<? include(ROOT_INC.'/search.inc'); ?>

<div class="spacer">&nbsp;</div>
<? include(ROOT_NAV.'/comunidad_side.inc'); ?>

<div class="spacer">&nbsp;</div>
<? include(ROOT_NAV.'/especial_side.inc'); ?>


</div>