<h2>Lista de correo</h2>
<div class="center" style="margin-right:15px; text-align: center;">
<form method="GET" action="http://es.groups.yahoo.com/subscribe/boulesis">
	  <label for="user" id="user" class="noshow">E-mail:</label>
	  <input type="text" name="user" value="escribe tu e-mail" size="15" class="formfield2" style="background-color: #EEE" onClick="this.value=''"/><br />
	  <label for="sendemail" id="sendemail" class="noshow">Enviar</label>
	  <input type="submit" value="Apúntate" name="sendemail" id="sendemail" class="formbutton2" style="margin-top: 0px"/>
</form>
<br /><a href="/didactica/comunidad/" title="Más información sobre nuestra comunidad online">Más info</a>
</div>