<div class="spacer">&nbsp;</div>
    <h2><em>Did&aacute;ctica</em></h2>
<div style="margin: 0 0 0 30px">
 <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- boulesis-enlaces-lateral -->
<ins class="adsbygoogle"
     style="display:inline-block;width:120px;height:90px"
     data-ad-client="ca-pub-7110432088770954"
     data-ad-slot="9686217572"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

<ul>
	<li><a href="/didactica/">Inicio didáctica</a></li>
	<li><a href="/didactica/apuntes/" title="Material educativo para filosofía">Apuntes</a></li>
	<li><a href="/didactica/textos/" title="Propuestas para ánalisis de escritos filosóficos">Comentarios de texto</a></li>
	<li><a href="/didactica/cuestionarios/" title="Tests para poner a prueba tus conocimientos">Cuestionarios</a></li>
	<li><a href="/didactica/documentos/" title="Almacén de archivos monográficos">Documentos</a></li>
	<li><a href="/didactica/enlaces/">Enlaces</a></li>
	<li><a href="/didactica/especiales/" title="Temas filosóficos tratados en profundidad">Especiales</a></li>
	<li><a href="/didactica/examenes/" title="Pruebas escritas de Filosofía, Ética, CTS y Psicología">Exámenes</a></li>
	<li><a href="/didactica/glosario/" title="Diccionario de términos filosóficos">Glosario</a></li>
	<li><a href="/didactica/logse/" title="Ayudas para comprender el sistema educativo español">LOGSE</a></li>
	<li><a href="/didactica/selectividad/" title="Pistas y recursos para realizar un buen examen de selectividad">Selectividad</a></li>
	<li><a href="/didactica/tutoria/" title="Blog de la tutoría de boulesis.com">Tutoría</a></li>
	<li><a href="/didactica/tics/" title="Tecnologías de Información y Comunicaciones. Aplicaciones educativas concretas">Tic's</a>
	<ul>
		<li><a href="/didactica/interactivos/" title="Juegos de filosofia en la web">Juegos interactivos</a></li>
		<li><a href="/didactica/webquests/" title="El nuevo sistema para realizar trabajos en grupo basados en internet">Webquests</a></li>
		<li><a href="/didactica/cazatesoros/" title="Actividad rápida con preguntas para investigación">Cazatesoros</a></li>
		</ul>
		</li>

	<li><a href="http://olimpiadafilosofica.com" title="Olimpiada filosófica para alumnos de Bachillerato. Click para ampliar"><img src="/olimpiada/media/logo-olimpiada-4.gif" width="100" height="42" border="1" /></a></li>
	<li><a href="http://www.boulesis.com/preparadores/"><img src="/preparadores/img/preparadores-oposiciones-pq.gif" width="121" height="84" alt="Preparadores de Oposiciones para la Enseñanza" border="0" /></a></li>
	<li><a href="/ayuda/rss/"><img src="/media/icon_rss.gif" alt="RSS de sindicaci&oacute;n de la didáctica y más" width="36" height="14" border="0" /></a></li>
</ul>

<h2><em>Comunidad</em></h2>
<ul>
	<li><a href="/didactica/comunidad/" title="Forma parte de la comunidad de boulesis.com: lista de correo y foros de debate">Comunidad online</a></li>
	<li><a href="/didactica/intercambio/" title="Ayúdanos a contruir una web cada vez más útil">Intercambio de materiales</a></li>
</ul>

<div class="spacer">&nbsp;</div>
<h2>Buscador</h2>
<? include(ROOT_INC.'/search.inc'); ?>

<div class="spacer">&nbsp;</div>
<? include(ROOT_NAV.'/comunidad_side.inc'); ?>

<div class="spacer">&nbsp;</div>
<? include(ROOT_NAV.'/especial_side.inc'); ?>

</div>