<div class="spacer">&nbsp;</div>
    <h2><em>Filos&oacute;fica</em></h2>
<ul>
	<li><a href="/filosofica/">Portada</a></li>
	<li><a href="/filosofica/miguel/">Personal</a></li>
	<? printSubmenu('miguel'); ?>
	<li><a href="/filosofica/etica-ciudadano-siglo-xxi/">Ética ciudadano</a></li>
	<li><a href="/filosofica/tesis/">Tesis</a></li>
	<? printSubmenu('tesis'); ?>
	<li><a href="/filosofica/tesina/">Tesina</a></li>
	<? printSubmenu('tesina'); ?>
	<li><a href="/filosofica/articulos/">Artículos</a></li>
	<? printSubmenu('articulos'); ?>
	<li><a href="/filosofica/comunicaciones/">Comunicaciones</a></li>
	<? printSubmenu('comunicaciones'); ?>	
	<li><a href="/filosofica/ponencias/">Ponencias</a></li>
	<? printSubmenu('ponencias'); ?>		
	<li><a href="http://olimpiada.boulesis.com" title="Olimpiada filosófica para alumnos de Bachillerato. Click para ampliar"><img src="/olimpiada/media/logo-olimpiada-4.gif" width="100" height="42" border="1" /></a></li>
</ul>

<div class="spacer">&nbsp;</div>
<? include(ROOT_INC.'/search.inc'); ?>

<div class="spacer">&nbsp;</div>
<? include(ROOT_NAV.'/comunidad_side.inc'); ?>

<div class="spacer">&nbsp;</div>
<? include(ROOT_NAV.'/especial_side.inc'); ?>


</div>