<div class="spacer">&nbsp;</div>
<img src="/media/dialbit/dialbit_logo.gif" width="375" height="60" alt="DialBit: Diálogo + Bitácoras. Un proyecto comunitario para debatir y reflexionar en la red sobre temas filosóficos y actuales" style="margin-left:15px;" />
<div class="submenudialbit">
<ul>
<li><a href="/boule/dialbit/">¿Qué es?</a></li>
<li><a href="/boule/dialbit/como.php">¿Cómo participo?</a></li>
<li><a href="/boule/dialbit/novedades.php">Novedades</a></li>
<li><a href="/boule/dialbit/participantes.php">Participantes</a></li>
<li><a href="/boule/dialbit/logos.php">Logos</a></li>
<li><a href="/boule/dialbit/apuntate.php">&raquo;Apúntate&laquo;</a></li>
<li><a href="/foros/verforo/12/">&raquo;Foro&laquo;</a></li>
<li><a href="/contacto">Contacto</a></li>
</ul>
</div>