<ul>
  <li><a href="/filosofica/miguel">Presentaci&oacute;n</a> </li>
  <li><a href="/filosofica/miguel/cv/formacion.php">Formaci&oacute;n</a> </li>
  <li><a href="/filosofica/miguel/cv/publicaciones.php">Publicaciones</a> </li>
  <li><a href="/filosofica/miguel/cv/otros.php">Otros m&eacute;ritos</a> </li>
  <li><a href="/filosofica/miguel/cv/experiencia.php">Experiencia</a> </li>
  <li><a href="/contacto">Contacto</a></li>
</ul>