<ul>
  <li><a href="/filosofica/ponencias">Presentaci&oacute;n</a> </li>
  <li><a href="/filosofica/ponencias/tic-aula/">&#8220;TIC's aula&#8221;</a> </li>
  <li><a href="/filosofica/ponencias/nuevas-tecnologias/">&#8220;Nuevas tecnologías&#8221;</a> </li>
  <li><a href="/filosofica/ponencias/herramientas-gratuitas/">&#8220;Herramientas gratis&#8221;</a> </li>
  <li><a href="/filosofica/ponencias/herramientas-4-eso/">&#8220;Herramientas 4º ESO&#8221;</a> </li>
<li><a href="/filosofica/ponencias/cap/">&#8220;Recursos enseñanza&#8221;</a> </li>
<li><a href="/filosofica/ponencias/cap2007metod/">"Metodología en ESo y Bachillerato"</a> </li>
<li><a href="/filosofica/ponencias/cap2007eval/">"Evaluación e innovación en el aula"</a> </li>
<li><a href="/filosofica/ponencias/colaborativo/">"Sobre el trabajo colaborativo"</a> </li>
  <li><a href="/filosofica/ponencias/masinformacion.php">Más información</a> </li>
</ul>