<ul>
  <li><a href="/filosofica/articulos">Presentaci&oacute;n</a> </li>
  <li><a href="/filosofica/articulos/calderon">"Calderón"</a> </li>
  <li><a href="/filosofica/articulos/dialectica">"Dialéctica"</a> </li>
  <li><a href="/filosofica/articulos/kantiana">"Kantiana"</a> </li>
  <li><a href="/filosofica/articulos/acordando">"Acordando"</a> </li>
  <li><a href="/filosofica/articulos/unamuno/">"Unamuno"</a> </li>
<li><a href="/filosofica/articulos/metodologia">"Enseñanza"</a></li>
<li><a href="/filosofica/articulos/hermeneutica">"Hermenéutica"</a></li>
<li><a href="/filosofica/articulos/rio-metafora">"Metafísica del río"</a></li>
  <li><a href="/filosofica/articulos/masinformacion.php">Más información</a> </li>

</ul>