La Diferencia,http://juglar103.blogspot.com/
Barraquito,http://www.barraquito.net
La Divina Comedia,http://www.blogia.com/vailima
Su Blog,http://www.susananajera.com/blog
Bicubic,http://www.bicubic.tk
Tio Petros,http://www.blogia.com/tiopetrus
AntroAzul,http://azul.f2o.org
Soveran,http://www.soveran.org/
Guerra eterna en Oriente Medio,http://ugarte63.blogspot.com/
La Oruga Gritona,http://laorugagritona.blogspot.com/
Fabián,http://www.blogia.com/fabian/
Cosimo,http://cosimo.bloxus.com/
Mensaje en una botella,http://mensajenabotella.blogspot.com/
ReflexionAndo,http://rabade.blogspot.com/
Seguro azar,http://underwoodgirls.f2o.org/weblog
Octaedro,http://octaedro.f2o.org/
El Palimpsesto,http://elpalimpsesto.blogspot.com/
El calamar te vigila,http://elcalamartevigila.blogspot.com/
Enre2,http://www.enre2.com.ar/
El lector,http://www.bibliotecadebabel.com/lector/
Escritos desde el páramo,http://fenix.blogia.com/
eWorkstation,http://www.eworkstation.homelinux.org/
Blog de viajes,http://www.blogdeviajes.com.ar/
Ana escribe,http://anaescribe.mibitacora.com/
Esencia divina,http://www.zonalibre.org/blog/esenciadivina
El patio de Violeta,http://e-violeta.blogspot.com/
Olvido,http://ondinaturquesa.blogspot.com/
Aprendiendo a vivir,http://joseluisl.blogspot.com/
Pensando,http://blogia.com/pienso
un minuto: una canción,http://www.blogia.com/unminutounacancion/
Rerum Varium,http://purl.org/net/rerum
Oniwabanshuu's,http://www.oniwabanshuu.tk/
de treinta y pico,http://treintaypico.bitacoras.com
The Raging Che,http://www.theragingche.com/blog/
Wimbledon,http://ultimasdebabel.blogspot.com
Monoaural,http://www.monmagan.com/monoaural/
jarabito,http://jarabito.blogspot.com 
Kahos,http://kahos.bitacoras.com 
Atún tun tun... Pensamientos en conserva,http://manuls.bitacoras.com
~Illussion Dream~,http://i-dream.allyenna.net 
Las chicas del 17,http://laschicasdel17.blogia.com/ 
DesignArt,http://designart.webcindario.com 
Frialdad.com,http://www.frialdad.com 
Escribiendo con la ziquierda,http://panaderiarobledano.com/backbit 
alexmoreno.net,http://www.alexmoreno.net 
Santuario,http://santuario.blogia.com  
Filosófica Suárez,http://www.jroller.com/page/cfilosofica
A Sueldo de Moscú,http://www.royo-villanova.net/
Desde mis gafas,http://amibola.blogspot.com/
Googleinfo,http://googleinfo.webcindario.com/
a·z·r·a·k,http://azrak.bitacoras.com
El paragüas rosa,http://www.elparaguasrosa.blogspot.com/
Duendecillo's place,http://duendecillo.bitacoras.com/
Diario de ivian,http://www.librexpresion.org/index.php?q=blog/476
Mi blog de notas,http://www.miblogdenotas.blogspot.com/
Vida de profesor,http://www.vidadeprofesor.blogia.com/
Blog de una profe,http://www.actilingua.net/blogdeunaprofedim.html
InicioÚtil,http://www.inicioutil.com/index.php