Hola!

Bienvenidos al diálogo entre bitácoras. En pocos días añadiremos un enalce a tu web dentro de DialBit.

No olvides pasarte por nuestras páginas donde te explican como funciona DialBit:
http://dialbit.boulesis.com
(no dejes de leer el apartado "¿Cómo participo?")

Y siempre puedes participar con sugerencias e ideas a través de nuestro foro de DialBit, donde no es necesario estar registrado para poder escribir:
http://www.boulesis.com/foros/verforo/12/

Gracias por tu participación
Equipo de boulesis.com